import streamlit as st

st.set_page_config(page_title="Terms of Service | IntelliMail")

st.title("📜 Terms of Service")

st.markdown("""
### 1. Acceptance of Terms
By using this internal tool, you agree to comply with IntelliMail's data handling standards.

### 2. AI Disclaimer
Analysis is generated by Artificial Intelligence. While high-precision, it should be verified by a professional before taking action on emails/professional use.

### 3. Jurisdiction
These terms are governed by the laws of the State of Arizona.
""")
